### PR TITLE
fix #13 adding gzCached option

### LINKED ISSUE #13: Option to not cache the list of .gz files
Hi, I would like to be able to turn off the behaviour of creation existent .gz files in the root, and be able serve generated .gz files after the initialization of the server.

### PR DESCRIPTION
**Pull request by danyg**
when set to false, checks file existence before serve, option value default true.

### CODE REVIEW

**Comment by pirxpilot** [comment]
Thanks. Alas, we should not use the `sync` version of the `fs.exists` every time we attempt to handle HTTP request. Check out [the initial implementation][1] for clues how to handle it properly.
It might be better to use the positive option value to trigger this behavior - as in `alwaysCheck: true` instead of `gzCached: false`. Also we should be able to do the check once only, when middleware is  initialized and pre-select the `exist` function we are going to use instead of deciding every time we handle the request. 


[1]: https://github.com/code42day/connect-gzip-static/blob/0.2.1/lib/gzip-static.js

**Comment by danyg** [comment]
Hi, yes I did a really quick fix just for a small server project, I wasn't really thinking about performance in matter of connection speed, I was thinking only about space saving.

So, what do you prefer? how deep in performance you want to get in? 
(A) we could do a lazy definition for the gzFileExists function when alwaysCheck is checked, mixed with the use of fs.exists will require to send a callback to be executed when gzFileExists get the result of the exists (in both scenarios) or..
(B) lazy definition of the entire middleware depending of this option you will save a function call there in the alwaysCheck false scenario. Also going in this direction some other change could be applied like:
- get rid of setHeader
- change  passToStatic = serveStatic.bind(this, req, res, next); for call return passToStatic.call(this, req, res, next); en the both cases that is happening, (creating the binding will consume time and memory which is not needed in the case of returning a .gz file).

**Comment by pirxpilot** [comment]
I am thinking (B) not so much for performance reasons but I kind of think code will be simpler / easier o understand and maintain.

> - get rid of setHeader

I am afraid I don't get this one. We have to set headers, right?

> change passToStatic = serveStatic.bind(this, req, res, next); for call return passToStatic.call(this, req, res, next);

Makes all kinds of sense. I'll do that (unless you get to it first of course).

**Comment by danyg** [comment]
Regarding the setHeaders, I'm not proposing to not send the headers, is just when you optimize a code to be "Hyper efficient" the first rule is to get rid of all the function calls as much as possible. Just because of that.
In the (B) scenario, I think will be more complex to be maintained, you probably end up with 2 codes  to be maintained, one for each option of alwaysCheck.
I'll take a look to this probably this weekend.

**Comment by danyg** [comment]
And this time I'll check the unit tests too :P

**Comment by pirxpilot** [comment]
> is just when you optimize a code to be "Hyper efficient" the first rule is to get rid of all the function calls as much as possible

OK. Let's not get crazy. We are not going for hyper-efficient here. We are going for _you shall not block the event loop when handling request_ :-)

**Pull request closed without merging**
